python3: set 'fork' start method
In Python 3 start method 'spawn' in multiprocessing module becomes
default on Mac OS [1].

The 'spawn' method causes re-execution of some code, which is already
executed in the main process. At least it is seen on the lib/__init__.py
code, which removes the 'var' directory. Some other code may have side
effects too, it requires investigation.

The method also requires object serialization that doesn't work when
objects use lambdas, whose for example used in class TestSuite
(lib/test_suite.py).

The latter problem is easy to fix, but the former looks more
fundamental. So we stick to the 'fork' method now.

The new start method is available on Python 3 only:

Traceback (most recent call last):
  File "../../test/test-run.py", line 227, in <module>
    multiprocessing.set_start_method('fork')
AttributeError: 'module' object has no attribute 'set_start_method'

1. https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods

Fixes #265
Part of #20

Co-authored-by: Alexander Turenko <alexander.turenko@tarantool.org>