Revert "Kill processes of non-started tarantool servers"
This reverts commit 9c2cc2d2699478536c6b254e20b4a48561c4dfe0.

The provided fix in mentioned commit is wrong. Many tests in tarantool
just install a server (without starting) and in such tests I can see the
following errors:

    [001] [2022-03-17 18:20:36.437767] DEBUG: [Instance proxy] Stopping the server...
    [001]
    [001] Test.run() received the following error:
    [001] Traceback (most recent call last):
    [001]   File "/Users/y.lobankov/Workspace/tarantool/test-run/lib/test.py", line 195, in run
    [001]     self.execute(server)
    [001]   File "/Users/y.lobankov/Workspace/tarantool/test-run/lib/tarantool_server.py", line 389, in execute
    [001]     ts.stop_nondefault(signal=signal.SIGKILL)
    [001]   File "/Users/y.lobankov/Workspace/tarantool/test-run/lib/preprocessor.py", line 443, in stop_nondefault
    [001]     v.stop(silent=True, signal=signal)
    [001]   File "/Users/y.lobankov/Workspace/tarantool/test-run/lib/tarantool_server.py", line 1026, in stop
    [001]     if self.process is not None and self.process.returncode is None:
    [001] AttributeError: 'TarantoolServer' object has no attribute 'process'
    [001]

If the server doesn't start, then the server object doesn't have the
`process` attribute.