ci: pin runner version to Ubuntu 20.04
Now the `ubuntu-latest` label points to Ubuntu 22.04 instead of 20.04.
Due to this fact, the testing workflow started to fail with an error
like this:

    Version 3.5 was not found in the local cache
    Error: Version 3.5 with arch x64 not found
    The list of all available versions can be found here:
    https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

Pin the runner version to Ubuntu 20.04 to avoid the error above.