requirements: bump gevent to 22.10.2
Bump `gevent` version to 22.10.2 to avoid the following issue with
installation in a Python 3.11 environment:

    In file included from src/gevent/_greenlet_primitives.c:1207:
    /tmp/pip-install-_f9yeixf/gevent_80c438d5f3944668ad39f6548d7ec03c/deps/greenlet/greenlet.h:42:5:
    error: unknown type name ‘CFrame’
       42 |     CFrame* cframe;
          |     ^~~~~~
    error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1

Version `23.*` doesn't support Python 3.7, so using the latest `22.*`
version.